name: "LineageUtilities"
version: 1.0.0
main: xyz.guyb.lineageutilities.main
api-version: 1.19
description: "A collection of server utilities."
load: POSTWORLD
authors:
  - Lineage_MC
website: guyb.xyz
softdepend:
  - LuckPerms

commands:
  # Fun Commands
  launch:
    description: Prepare for liftoff.
    permission: lineageUtilities.launch

  demo:
    permission: lineageUtilities.demo

  # Utility Commands
  heal:
    description: Heals a player to full health and hunger.
    permission: lineageUtilities.heal
    aliases:
      - genji
      - iNeedHealing

  survival:
    description: Changes the player's mode to survival
    permission: lineageUtilities.survival
    aliases:
      - gms

  creative:
    description: Changes the player's mode to creative
    aliases:
      - gmc

  spectator:
    description: Changes the player's mode to spectator
    aliases:
      - gmsp

  adventure:
    description: Changes the player's mode to adventure.
    permission: lineageUtilities.adventure
    aliases:
      - gma

  discord:
    description: Shows a discord link.
    permission: lineageUtilities.discord

  bed:
    description: Teleports the player to their bed if they have one set.
    permission: lineageUtilities.bed
    aliases:
      - home
      - bedTP

  ping:
    description: Shows a player's latency to the server in milliseconds.
    permission: lineageUtilities.ping

  fly:
    description: Toggles a whether a player can fly or not.
    permission: lineageUtilities.fly

  broadcast:
    description: Broadcasts a message to the entire server.
    permission: lineageUtilities.broadcast

  spawn:
    description: Sends a player to spawn.
    permission: lineageUtilities.spawn

permissions:

  # Fun Permissions
  lineageUtilities.launch:
    default: op

  lineageUtilities.demo:
    default: op
  # Utility Permissions
  lineageUtilities.discord:
    default: true

  lineageUtilities.broadcast:
    default: op

  lineageUtilities.bed:
    default: true

  lineageUtilities.bed.others:
    default: op

  lineageUtilities.ping:
    default: true

  lineageUtilities.ping.others:
    default: true

  lineageUtilities.fly:
    default: op

  lineageUtilities.fly.others:
    default: op

  lineageUtilities.creative:
    default: op

  lineageUtilities.survival:
    default: op

  lineageUtilities.spectator:
    default: op

  lineageUtilities.adventure:
    default: op

  lineageUtilities.creative.other:
    default: op

  lineageUtilities.survival.other:
    default: op

  lineageUtilities.spectator.other:
    default: op

  lineageUtilities.adventure.other:
    default: op

  lineageUtilities.heal:
    default: op

  lineageUtilities.heal.other:
    default: op