name: "LineageUtilities"
version: 1.0.0
main: xyz.guyb.lineageutilities.main
api-version: 1.19
description: "A collection of server utilities."
load: STARTUP
authors:
  - Lineage_MC
website: guyb.xyz
depend:
  - LuckPerms

commands:
  # Fun Commands
  launch:
    description: Prepare for liftoff.
    permission: lineageutilities.launch

  # Utility Commands
  bedtp:
    description: Teleports the player to their bed if they have one set.
    permission: lineageutilities.bedteleport
    aliases:
      - home
      - bed

  ping:
    description: Shows a player's latency to the server in milliseconds.
    permission: lineageutilities.ping

  fly:
    description: Toggles a whether a player can fly or not.
    permission: lineageutilities.fly

  broadcast:
    description: Broadcasts a message to the entire server.
    permission: lineageutilities.broadcast

permissions:
  # Fun Permissions
  lineageutilities.launch:
    default: op

  # Utility Permissions
  lineageutilities.broadcast:
    default: op

  lineageutilities.bedteleport:
    default: true

  lineageutilities.ping:
    default: true

  lineageutilities.ping.others:
    default: true

  lineageutilities.fly:
    default: op

  lineageutilities.fly.others:
    default: op