name: "LineageUtilities"
version: 1.0.0
main: xyz.guyb.lineageutilities.main
api-version: 1.19
description: "A collection of server utilities."
load: STARTUP
authors:
  - Lineage_MC
website: guyb.xyz
depend:
  - LuckPerms

commands:
  launch:
    permission: lineageutilities.commands.fun.Launch
    description: Prepare for liftoff.

  bedtp:
    permission: lineageutilities.commands.utility.BedTeleport
    description: Teleports the player to their bed if they have one set.
    aliases:
      - home
      - bed

permissions:
  # Fun Permissions
  lineageutilities.commands.fun.Launch:
    default: op

  # Utility Permissions
  lineageutilities.commands.utility.BedTeleport:
    default: true

